### ISSUE TITLE
Is there any documentation on how to make a request? 

### ISSUE THREAD

**Issue by onnttf** [octokit/go-sdk#86]
Hello, I want to get the release list of a repo. Is there any relevant document?

Here is my code:

```golang
tokenProvider := auth.NewTokenProvider(
	// to create an authenticated provider, uncomment the below line and pass in your token
	// auth.WithTokenAuthentication("ghp_your_token"),
	auth.WithUserAgent("octokit/go-sdk.example-functions"),
)
adapter, err := kiotaHttp.NewNetHttpRequestAdapter(tokenProvider)
if err != nil {
	log.Fatalf("Error creating request adapter: %v", err)
}

var p *int32 = new(int32)
*p = 1

var p1 *int32 = new(int32)
*p1 = 1

resp, err := repos.
	NewItemItemReleasesRequestBuilder("https://github.com/octokit/go-sdk", adapter).
	Get(context.Background(), &abstractions.RequestConfiguration[repos.ItemItemReleasesRequestBuilderGetQueryParameters]{
		QueryParameters: &repos.ItemItemReleasesRequestBuilderGetQueryParameters{
			Page:     p,
			Per_page: p1,
		},
	})
if err != nil {
	panic(err)
}
fmt.Print(resp)
```

Here is the error message:

```
panic: content type application/json does not have a factory registered to be parsed
```

How should I modify it?

**Comment by onnttf** [comment]
Here is my code:

```golang
tokenProvider := auth.NewTokenProvider(
	// to create an authenticated provider, uncomment the below line and pass in your token
	// auth.WithTokenAuthentication("ghp_your_token"),
	auth.WithUserAgent("octokit/go-sdk.example-functions"),
)
adapter, err := kiotaHttp.NewNetHttpRequestAdapter(tokenProvider)
if err != nil {
	log.Fatalf("Error creating request adapter: %v", err)
}

var p *int32 = new(int32)
*p = 1

var p1 *int32 = new(int32)
*p1 = 1

resp, err := repos.
	NewItemItemReleasesRequestBuilder("https://github.com/octokit/go-sdk", adapter).
	Get(context.Background(), &abstractions.RequestConfiguration[repos.ItemItemReleasesRequestBuilderGetQueryParameters]{
		QueryParameters: &repos.ItemItemReleasesRequestBuilderGetQueryParameters{
			Page:     p,
			Per_page: p1,
		},
	})
if err != nil {
	panic(err)
}
fmt.Print(resp)
```

Here is the error message:

```
panic: content type application/json does not have a factory registered to be parsed
```

How should I modify it?

**Comment by kfcampbell** [comment]
It's definitely a bit confusing, since our OpenAPI spec isn't always perfectly normalized and we have a whole bunch of models to use, and there's a lot of Kiota helpers generated as well. 

Here's the approach I've found helpful (and maybe we should add this to the docs somewhere): 

- First, find the docs link for what you want. In this case, that's https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#list-releases. 
- Next, search `go-sdk` for that docs link, since Kiota includes the docs link when generating models. Note that Kiota leaves out the `/en` and the `apiVersion` parameter, so the docs link to search for becomes https://docs.github.com/rest/releases/releases#list-releases. This gives us https://github.com/octokit/go-sdk/blob/a379f572bf4cea19390cf5b74c09cf7ce010004c/pkg/github/repos/item_item_releases_request_builder.go#L59. Note that the `item_item_releases_request_builder` belongs to the `repos` package.
- Now you can take this information and write code to call it in the example CLI (or wherever). Here's a working example, assuming an initialized `client`:

```go
	releases, err := client.Repos().ByOwnerId("octokit").ByRepoId("go-sdk").Releases().Get(context.Background(), nil)
	if err != nil {
		log.Fatalf("error getting releases: %v", err)
	}
	log.Printf("Releases:\n")
	for _, release := range releases {
		log.Printf("Tag: %v\n", *release.GetTagName())
		log.Printf("Notes: %v\n", *release.GetBody())
	}
```

I hope that helps!

**Comment by onnttf** [comment]
Thank you very much for your help, it solved my problem.
